// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates cup art based on a description of the event theme.
 *
 * - generateCupArt - A function that generates cup art based on an event theme description.
 * - GenerateCupArtInput - The input type for the generateCupArt function.
 * - GenerateCupArtOutput - The return type for the generateCupArt function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCupArtInputSchema = z.object({
  cupModel: z.string().describe('The model of the cup to generate art for.'),
  eventDescription: z.string().describe('A description of the event theme, including details like theme, phrases, names, and date.'),
});
export type GenerateCupArtInput = z.infer<typeof GenerateCupArtInputSchema>;

const GenerateCupArtOutputSchema = z.object({
  generatedArt: z.string().describe('The generated art for the cup, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.'),
});
export type GenerateCupArtOutput = z.infer<typeof GenerateCupArtOutputSchema>;

export async function generateCupArt(input: GenerateCupArtInput): Promise<GenerateCupArtOutput> {
  return generateCupArtFlow(input);
}

const generateCupArtFlow = ai.defineFlow(
  {
    name: 'generateCupArtFlow',
    inputSchema: GenerateCupArtInputSchema,
    outputSchema: GenerateCupArtOutputSchema,
  },
  async input => {
    const fullPrompt = `Generate a high-quality visual design for a ${input.cupModel} cup. The design should be based on the following event description: "${input.eventDescription}". The final image must have a transparent background and be suitable for printing.`;

    const {media} = await ai.generate({
      model: 'googleai/gemini-2.0-flash-preview-image-generation',
      prompt: fullPrompt,
      config: {
        responseModalities: ['TEXT', 'IMAGE'], // MUST provide both TEXT and IMAGE, IMAGE only won't work
      },
    });
    if (!media) {
      throw new Error('no media returned');
    }
    return {generatedArt: media.url};
  }
);
